- name: Drider (Grande)
  image: /products/Drider (Grande).png
  link: https://buy.stripe.com/9B63cv8Fv8hvgSqeTeffy06

- name: Orrore Sotterraneo (Grande)
  image: /products/Orrore Sotterraneo (Grande).png
  link: https://buy.stripe.com/dRm4gz5tj41f9pY8uQffy07

- name: Ragno (Grande)
  image: /products/Ragno (Grande).png
  link: https://buy.stripe.com/9B628raND1T7by66mIffy08

- name: Spectator (Grande)
  image: /products/Spectator (Grande).png
  link: https://buy.stripe.com/9B67sL5tj8hv9pY3awffy09

- name: Ombra (Medio)
  image: /products/Ombra (Medio).png
  link: https://buy.stripe.com/9B67sLcVLeFT7hQ26sffy0a

- name: Professor Talpa (Medio)
  image: /products/Professor Talpa (Medio).png
  link: https://buy.stripe.com/bJe5kDcVLgO1eKi9yUffy0b
